spring:
  datasource:
    username: 数据库用户名
    password: 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 数据库url
    hikari:
      idle-timeout: 60000
      max-lifetime: 65000
      minimum-idle: 2
      maximum-pool-size: 8
  redis:
    host: redis地址
    port: 6379
    password: redis密码
    database:
      db0: 0
      db1: 1
      db2: 2
    lettuce:
      pool:
        max-active: 100
        max-idle: 3
        min-idle: 0
        max-wait: -1
  cloud:
    nacos:
      discovery:
        server-addr: nacos地址
        namespace: public
        username: nacos用户名
        password: nacos密码
        service: 服务组名称
        ip: 应该发布的ip
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: 服务组名称
          uri: lb://服务组名称
          predicates:
            - Path=/应当代理的url/**
mybatis:
  mapper-locations: classpath:mappers/*.xml
server:
  address: 127.0.0.1
  port: 4000